# Generated by Django 3.1.2 on 2020-10-14 13:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatgerapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='cdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
