# Generated by Django 3.1.2 on 2020-10-14 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatgerapp', '0002_city_cdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='cdate',
        ),
    ]
